### ISSUE TITLE
Does not stack everything above max version 1.20.1

### ISSUE THREAD

**Issue by Lord-Infinity** [AverageAnime/StackSizeEdit#10]
Hello,

I have a gunmod installed called TACZ. Its ammunition does not stack above its max size. How can I fix this?

Thanks in advance.

**Comment by AverageAnime** [comment]
TACZ controls the ammo max stack size in a unique way, I think due to how the ammo boxes work. I don't have any idea how to make Stack Size Edit work with how it modifies stack size,  but TACZ allows you to manually set the stack of each ammo type with a resource pack. https://github.com/MCModderAnchor/TACZ/tree/1.20.1/src/main/resources/assets/tacz/custom/tacz_default_gun/tacz/ammo/index

**Comment by Lord-Infinity** [comment]
Bigger Stacks can make tacz ammunition stack but its sadly only for forge
